### ISSUE TITLE
Nades on Car

### ISSUE THREAD

**Issue by momoplayer** [szabto/PromodLive220#1]
Hi mate,
First of all, thanks for this Promod. It is a really nice work so far...
Just wanted to let you know that cars don't explode if you throw a nade at them. They do explode if you shoot them. Also the Burning animation of cars misses.

It would be nice, if you can fix this.

Greets.
Momo

**Comment by szabto** [comment]
I'm gonna check it, thanks for reporting!

**Comment by szabto** [comment]
Fixed, and commited changes.
Forgot to add destructible.csv, i forgot its added in 220. :P 

Thank you.
